version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "miniforge3-26.3"
  jobs:
    install:
      - python -m pip install --no-deps .

conda:
  environment: environment-docs.yml

formats:
  - epub
  - pdf

sphinx:
  configuration: docs/source/conf.py